### ISSUE TITLE
Problem with $filter and name with accentuation in return

### ISSUE THREAD

**Issue by marciotheis** [flat3/lodata#285] opened 2022-06-22 18:07 UTC
Hi,

When trying to apply $filter in a request where the name of a person has accentuation it's generated an error:

```
{"@context":"http://localhost:8050/odata/$metadata#persons(idperson,name)","value":[{"idperson":1138,"name":
TypeError: Flat3\Lodata\Helper\JSON::encode(): Return value must be of type string, bool returned in file C:\Projects\oData\vendor\flat3\lodata\src\Helper\JSON.php on line 33

#0 C:\Projects\oData\vendor\flat3\lodata\src\Controller\Transaction.php(1035): Flat3\Lodata\Helper\JSON::encode()
#1 C:\Projects\oData\vendor\flat3\lodata\src\Primitive.php(129): Flat3\Lodata\Controller\Transaction->sendJson()
#2 C:\Projects\oData\vendor\flat3\lodata\src\ComplexValue.php(344): Flat3\Lodata\Primitive->emitJson()
#3 C:\Projects\oData\vendor\flat3\lodata\src\EntitySet.php(221): Flat3\Lodata\ComplexValue->emitJson()
#4 C:\Projects\oData\vendor\flat3\lodata\src\EntitySet.php(281): Flat3\Lodata\EntitySet->emitJson()
#5 C:\Projects\oData\vendor\symfony\http-foundation\StreamedResponse.php(93): Flat3\Lodata\EntitySet->Flat3\Lodata\{closure}()
#6 C:\Projects\oData\vendor\flat3\lodata\src\Controller\Response.php(96): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#7 C:\Projects\oData\vendor\flat3\lodata\src\Controller\Response.php(144): Flat3\Lodata\Controller\Response->sendContentStreamed()
#8 C:\Projects\oData\vendor\flat3\lodata\src\Helper\Symfony\Response6.php(17): Flat3\Lodata\Controller\Response->_sendContent()
#9 C:\Projects\oData\vendor\symfony\http-foundation\Response.php(373): Flat3\Lodata\Helper\Symfony\Response6->sendContent()
#10 C:\Projects\oData\public\index.php(53): Symfony\Component\HttpFoundation\Response->send()
#11 {main}
```

Request
`http://localhost:8050/odata/persons?$select=idperson,name&top=2&filter=contains(name, 'Vitor')&skip=1`

Although, if I do the request directly like http://localhost:8050/odata/persons/1138 its works without problem.
Thank you for your time !

**Comment by 27pchrisl** [comment] 2022-06-22 19:13
Hi @marciotheis, I wasn't able to immediately reproduce this - could you provide an example of the accentuation in the field content that's causing the issue? Also the column type and character set in use by the database could help. Thanks!

**Comment by marciotheis** [comment] 2022-06-22 20:51
Hi @27pchrisl, I attached an example, where it's used SQL Server 2016 or 2019 and the database colletion is Latin1_General_CI_AI or Latin1_General_CI_AS

Request
`http://localhost:8050/odata/persons?filter=contains(firstname, 'V')`

Thank !
[example.zip](https://github.com/flat3/lodata/files/8961207/example.zip)

**Comment by 27pchrisl** [comment] 2022-06-23 08:58
Hi @marciotheis, still no luck - which PHP version are you using?
I made a change to the 5.x branch to make `json_encode` throw on error.
Could you `composer require flat3/lodata:dev-5.x` ? It will still have the issue but hopefully with a more useful error message!

**Comment by marciotheis** [comment] 2022-06-23 12:35
Hi @27pchrisl 

I did the update, and the new message generated is:
```
{"@context":"http://localhost:8000/odata/$metadata#persons","value":[{"idperson":1,"firstname":
JsonException: Malformed UTF-8 characters, possibly incorrectly encoded in file C:\Projects\odata\vendor\flat3\lodata\src\Helper\JSON.php on line 34

#0 C:\Projects\odata\vendor\flat3\lodata\src\Helper\JSON.php(34): json_encode()
#1 C:\Projects\odata\vendor\flat3\lodata\src\Controller\Transaction.php(1035): Flat3\Lodata\Helper\JSON::encode()
#2 C:\Projects\odata\vendor\flat3\lodata\src\Primitive.php(129): Flat3\Lodata\Controller\Transaction->sendJson()
#3 C:\Projects\odata\vendor\flat3\lodata\src\ComplexValue.php(344): Flat3\Lodata\Primitive->emitJson()
#4 C:\Projects\odata\vendor\flat3\lodata\src\EntitySet.php(221): Flat3\Lodata\ComplexValue->emitJson()
#5 C:\Projects\odata\vendor\flat3\lodata\src\EntitySet.php(281): Flat3\Lodata\EntitySet->emitJson()
#6 C:\Projects\odata\vendor\symfony\http-foundation\StreamedResponse.php(93): Flat3\Lodata\EntitySet->Flat3\Lodata\{closure}()
#7 C:\Projects\odata\vendor\flat3\lodata\src\Controller\Response.php(96): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#8 C:\Projects\odata\vendor\flat3\lodata\src\Controller\Response.php(144): Flat3\Lodata\Controller\Response->sendContentStreamed()
#9 C:\Projects\odata\vendor\flat3\lodata\src\Helper\Symfony\Response6.php(17): Flat3\Lodata\Controller\Response->_sendContent()
#10 C:\Projects\odata\vendor\symfony\http-foundation\Response.php(373): Flat3\Lodata\Helper\Symfony\Response6->sendContent()
#11 C:\Projects\odata\public\index.php(53): Symfony\Component\HttpFoundation\Response->send()
#12 {main}
```

I'm using php version 8.1.4 and this is my php.ini
[php.txt](https://github.com/flat3/lodata/files/8967120/php.txt)

**Request examples**
![image](https://user-images.githubusercontent.com/20651229/175298486-dafe3df2-5214-412e-acea-a4b2b1f47f2e.png)

![image](https://user-images.githubusercontent.com/20651229/175299142-137408e3-46bc-4d8d-8a66-7bf2ff5bb092.png)

Thanks !

**Comment by 27pchrisl** [comment] 2022-06-23 15:53
Hi, still no luck, but this seems to be describing a similar issue to https://stackoverflow.com/questions/18247737/json-encode-produce-json-error-utf8-from-mssql-select

Does your database.php include the `'charset' => 'utf8'` option?
Could you send the output of `php -i` to verify the Microsoft PDO drivers are being loaded?

Very strange that the single version works and the filter does not. Does this give the error: `http://localhost:8050/odata/persons` ?

**Comment by 27pchrisl** [comment] 2022-06-23 16:05
Another thing to try according to https://docs.microsoft.com/en-us/sql/connect/php/how-to-send-and-retrieve-utf-8-data-using-built-in-utf-8-support

Setting `'charset' => 'UTF-8'` (instead of 'utf8') in the database.sql, or removing this array entry completely.

According to https://docs.microsoft.com/en-us/sql/connect/php/retrieving-data-as-a-stream-using-the-sqlsrv-driver there may be some difference in how this is handled on Windows (I'm using SQL Server on Linux). If the driver doesn't understand 'utf8' as a charset, it might interpret it as `SQLSRV_ENC_CHAR`.

**Comment by marciotheis** [comment] 2022-06-23 19:02
Hi @27pchrisl 

I did all the tests, changing the charset to UTF-8 and even removing the entry. However, in every test I got the same error.
This is my php -i
[i.txt](https://github.com/flat3/lodata/files/8970156/i.txt)

Executing http://localhost:8050/odata/persons
![image](https://user-images.githubusercontent.com/20651229/175376509-7e66dece-a23d-4c00-bba8-aa250ad6e59c.png)

I did a test in src/Drivers/EloquentEntitySet.php function query() where I commited those lines:
```
        $where = $this->generateWhere();
        if ($where->hasStatement()) {
            $builder->whereRaw($where->getStatement(), $where->getParameters());
        }
```
I get all the records, but, without errors.
Seems like something change in the model when isn't applicated the $where.

![image](https://user-images.githubusercontent.com/20651229/175377389-0a901de8-87a2-49d0-b598-1242c08d166d.png)

Thank you again!

**Comment by marciotheis** [comment] 2022-06-23 20:01
Hi @27pchrisl 

I did a new test, and work for me.

In src/Drivers/SQL/SQLConnection.php
```
        if ($dbh->getAttribute(PDO::ATTR_DRIVER_NAME) === SQLEntitySet::SQLServer) {
            $dbh->setAttribute(PDO::SQLSRV_ATTR_ENCODING, PDO::SQLSRV_ENCODING_SYSTEM);
        }
```
I changed to:
```
        if ($dbh->getAttribute(PDO::ATTR_DRIVER_NAME) === SQLEntitySet::SQLServer) {
            $dbh->setAttribute(PDO::SQLSRV_ATTR_ENCODING, PDO::SQLSRV_ENCODING_UTF8);
        }
```

Even if I comment those two lines works without problems.

![image](https://user-images.githubusercontent.com/20651229/175386778-acb82c5d-2270-498a-baad-e9b156d8707c.png)

Could you considered change the code in SQLConnection.php ?

Thanks !

**Comment by 27pchrisl** [comment] 2022-06-24 08:35
Good spot! I had not realised that this code would change the connection properties for the pooled connection, and the tests all pas without it. So I have removed it as Lodata should not be changing attributes of the connection. Can you check again with the 5.x-dev version?

**Comment by marciotheis** [comment] 2022-06-24 11:47
Hi @27pchrisl 

I did new tests with the 5.x-dev version, and work.

Thanks!

**Comment by 27pchrisl** [comment] 2022-06-24 13:26
Resolved in https://github.com/flat3/lodata/releases/tag/v5.18.0

**Closed as completed by 27pchrisl** 2022-06-24 13:26 UTC
