### ISSUE TITLE
No Eager Loading ?

### ISSUE THREAD

**Issue by Iseldore** [flat3/lodata#110] opened 2021-09-02 10:03 UTC
Hi,

When I use $expand, I have over 200 queries because eager loading is not used. 

Could you please update package or tell me how to enable eager loading ? 

Thanks !

**Comment by 27pchrisl** [comment] 2021-09-02 12:42
Hiya @Iseldore thanks for the report! To reproduce what's causing these extra queries could you share a bit more about your setup like the EntitySet types in use (Eloquent vs SQL), how they're related and the OData URL query parameters you're using?

**Comment by Iseldore** [comment] 2021-09-02 13:22
Sure, it looks like that :

In AppServiceProvider : 
` \Lodata::discoverEloquentModel(\App\Models\Address::class);`
`\Lodata::discoverEloquentModel(\App\Models\User::class);`
`\Lodata::getEntitySet('Users')->discoverRelationship('addresses');`

The request is `/odata/Users?$expand=addresses`

**Comment by Iseldore** [comment] 2021-09-02 14:31
No changes here :
![image](https://user-images.githubusercontent.com/11499656/131862317-843a61f6-11e4-4fce-90a1-3ed7d6eeef55.png)

still having a select on each users + select on addresses table for each user

**Comment by 27pchrisl** [comment] 2021-09-02 16:51
This is tricky to completely fix, because Lodata doesn't perform a real database join for expanded entities.

However, as you point out Lodata is doing three queries for each entity, where two of them are unnecessary. I have released v2.1.3 that should eliminate at least 2/3rds of the queries.

Converting the way expansion works to eager load using a proper join is something I will look into as well.

**Comment by Iseldore** [comment] 2021-09-02 18:40
Thank you for your reactivity, I confirm that I have less requests now ! 😄 

However, it would be great if you could perform that with no n+1 queries. 

Thanks you again and for your great package !

**Comment by masterix21** [comment] 2023-02-17 16:13
I can confirm that the package does a lot of queries because don't use the eager loading feature.

**Comment by RuslanMelnychenko** [comment] 2023-03-11 11:00
I fixed it
Replace the function [`EloquentEntitySet::query()`](https://github.com/flat3/lodata/blob/5.x/src/Drivers/EloquentEntitySet.php#L262) and add new function `EloquentEntitySet::getRelationships()`

```php
/**
 * Query eloquent models
 */
public function query(): Generator
{
    $builder = $this->getBuilder();
    $builder->select('*');

    if ($this->navigationSource) {
        /** @var Entity $sourceEntity */
        $sourceEntity = $this->navigationSource->getParent();
        $expansionPropertyName = $sourceEntity->getEntitySet()->getPropertySourceName($this->navigationSource->getProperty());
        /** @var Model $source */
        $source = $sourceEntity->getSource();
        $expansionBuilder = $source->$expansionPropertyName();

        if ($source->relationLoaded($expansionPropertyName)) {
            $relation = \Illuminate\Support\Collection::wrap($source->getRelation($expansionPropertyName));
            foreach ($relation->lazy() as $model) {
                yield $this->modelToEntity($model);
            }
            return;
        }
        $builder = $expansionBuilder;
        if ($builder instanceof HasManyThrough) {
            $builder->select($builder->getRelated()->getTable().'.*');
        }
    }

    $this->implementParametersInBuilder($builder);

    $builder->with($this->getRelationships());

    foreach ($builder->lazy() as $model) {
        yield $this->modelToEntity($model);
    }
}

/**
 * Implement $compute, $top, $skip, $orderby, $filter, $search to Builder
 * @param $builder
 * @return void
 */
protected function implementParametersInBuilder($builder) {
    $this->selectComputedProperties($builder);

    $where = $this->generateWhere();

    if ($where->hasStatement()) {
        $builder->whereRaw($where->getStatement(), $where->getParameters());
    }

    $orderby = $this->generateOrderBy();

    if ($orderby->hasStatement()) {
        $builder->orderByRaw($orderby->getStatement(), $orderby->getParameters());
    }

    if ($this->getTop()->hasValue()) {
        $builder->limit($this->getTop()->getValue());
    }

    if ($this->getSkip()->hasValue()) {
        if (!$this->getTop()->hasValue()) {
            $builder->limit(PHP_INT_MAX);
        }

        $builder->skip($this->getSkip()->getValue());
    }
}

/**
 * Get relations by navigation requests
 * @return array
 */
protected function getRelationships(): array
{
    $relations = [];

    foreach ($this->getType()->getNavigationProperties() as $navigationProperty) {
        $navigationRequest = $this->getTransaction()->getNavigationRequests()->get($navigationProperty->getName());
        if (!$navigationRequest) {
            continue;
        }
        $expansionPropertyName = $this->getPropertySourceName($navigationProperty);
        $expansionTransaction = clone $this->getTransaction();
        $expansionTransaction->setRequest($navigationRequest);
        $expansionSet = clone $this->getBindingByNavigationProperty($navigationProperty)->getTarget();
        $expansionSet->setTransaction($expansionTransaction);
        $relations[$expansionPropertyName] = function ($builder) use ($expansionSet) {
            $expansionSet->implementParametersInBuilder($builder);
        };
        $relations = array_merge(
            $relations,
            \Illuminate\Support\Arr::prependKeysWith(
                $expansionSet->getRelationships(),
                "{$expansionPropertyName}."
            )
        );
    }

    return $relations;
}
```

<details>
<summary>Example (Laravel Telescope)</summary>

## Request

![image](https://user-images.githubusercontent.com/30592345/224479896-b15c6e13-f4c4-4d6f-9d64-a470047d9737.png)

### Before:

![image](https://user-images.githubusercontent.com/30592345/224480068-80623e85-148d-41d1-9c9a-00d1d4841b86.png)

### After:

![image](https://user-images.githubusercontent.com/30592345/224480172-640df74f-9bd6-4771-bb8a-9e48decb1e41.png)

_PS: -1 query for authentication_
</details>

I'm not sure if this is the right approach, but it works 😎

**Comment by 27pchrisl** [comment] 2023-03-11 14:55
Thanks for this great work @RuslanMelnychenko ! I have created a PR to get it included... #523

**Comment by 27pchrisl** [comment] 2023-03-18 18:34
This contribution now merged.

**Closed by 27pchrisl** 2023-03-18 18:34 UTC
