### ISSUE TITLE
$metadata query returns 500 error

### ISSUE THREAD

**Issue by jmanring** [flat3/lodata#271] opened 2022-06-07 19:34 UTC
Querying http://127.0.0.1:8080/odata/$metadata returns a 500 error. 

This is a simple mysql database table with 6 columns. One column, with a datatype or timestamp, uses CURRENT_TIMESTAMP as the default expression. 
```
Field                 Type         Null KEY  Default
id                    int(11)      NO		
remote_id             bigint(20)   NO   PRI	
name                  varchar(100) NO		
status                varchar(20)  NO		
date_added            timestamp    NO        CURRENT_TIMESTAMP
lastModifiedDateTime  timestamp    YES		
```

The provider code is:
```
$entityType = new EntityType('mytable');
$entitySet = (new \Flat3\Lodata\Drivers\SQLEntitySet('mytable', $entityType))
    ->setTable('mytable')
    ->discoverProperties();
\Lodata::add($entitySet);
```

The log output is:
```
[2022-06-07 18:50:43] local.ERROR: DateTimeImmutable::__construct(): Failed to parse time string (CURRENT_TIMESTAMP) at position 0 (C): The timezone could not be found in the database {"exception":"[object] (Carbon\\Exceptions\\InvalidFormatException(code: 0): DateTimeImmutable::__construct(): Failed to parse time string (CURRENT_TIMESTAMP) at position 0 (C): The timezone could not be found in the database at /odata-laravel/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:89)
[stacktrace]
#0 /odata-laravel/vendor/flat3/lodata/src/Type/DateTimeOffset.php(45): Carbon\\CarbonImmutable->__construct()
#1 /odata-laravel/vendor/flat3/lodata/src/Primitive.php(57): Flat3\\Lodata\\Type\\DateTimeOffset->set()
#2 /odata-laravel/vendor/flat3/lodata/src/PrimitiveType.php(53): Flat3\\Lodata\\Primitive->__construct()
#3 /odata-laravel/vendor/flat3/lodata/src/Property.php(303): Flat3\\Lodata\\PrimitiveType->instance()
#4 /odata-laravel/vendor/flat3/lodata/src/PathSegment/Metadata/XML.php(161): Flat3\\Lodata\\Property->computeDefaultValue()
#5 /odata-laravel/vendor/flat3/lodata/src/PathSegment/Metadata/XML.php(350): Flat3\\Lodata\\PathSegment\\Metadata\\XML->emitStream()
#6 /odata-laravel/vendor/symfony/http-foundation/StreamedResponse.php(109): Flat3\\Lodata\\PathSegment\\Metadata\\XML->Flat3\\Lodata\\PathSegment\\Metadata\\{closure}()
#7 /odata-laravel/vendor/flat3/lodata/src/Controller/Response.php(96): Symfony\\Component\\HttpFoundation\\StreamedResponse->sendContent()
#8 /odata-laravel/vendor/flat3/lodata/src/Controller/Response.php(144): Flat3\\Lodata\\Controller\\Response->sendContentStreamed()
#9 /odata-laravel/vendor/flat3/lodata/src/Helper/Symfony/Response5.php(17): Flat3\\Lodata\\Controller\\Response->_sendContent()
#10 /odata-laravel/vendor/symfony/http-foundation/Response.php(394): Flat3\\Lodata\\Helper\\Symfony\\Response5->sendContent()
#11 /odata-laravel/public/index.php(53): Symfony\\Component\\HttpFoundation\\Response->send()
#12 /odata-laravel/server.php(21): require_once('/...')
#13 {main}
```

**Comment by otmaneEH** [comment] 2022-06-07 19:44
THE CODE TO COPY AND PASTE
composer install 
mv .env.example .env 
php artisan cache:clear 
composer dump-autoload 
php artisan key:generate

**Comment by 27pchrisl** [comment] 2022-06-07 20:27
Thanks for the report! I have pushed a change to the 5.x branch that should resolve this issue, which is that Lodata did not correctly parse default values that are SQL keywords (like CURRENT_TIMESTAMP).

Could you `composer require flat3/lodata:dev-5.x` and verify the issue is fixed?

**Comment by 27pchrisl** [comment] 2022-06-07 20:34
Fixed in https://github.com/flat3/lodata/releases/tag/v5.16.0

**Closed as completed by 27pchrisl** 2022-06-07 20:34 UTC
